---
title: "ResearchNotes"
author: "Rob Hayward"
date: "1 November 2015"
output: 
  html_document: 
    toc: yes
---

#Regime-switching method
[Modelling time-varying variation in euro-lending spreads](http://www.bis.org/publ/work526.htm) BIS paper that looks at regime shift in a VAR model of lending passthourgh.  It uses a number of variables to model the regime-switch.  There are endogenous transiation-probabilities finds that global risk factors have contributed to higher lending rates in Italy and Spain while banking problems explain problems in Spain and fiscal and contaigion problems have affected Italy and Ireland. ECB extraordinary measures have had a temporary effect on Italy policy. There do not appear to be changes in the monetary policy transmission for Portugal. 

The financial crisis necessitated the use of non-linear modelling techniques. Silverstrini and Zaghini (2015) explore the non-linear links between financial and real sectors. There are moentary frameworks with regimes-shifts like Svensson and Williams (2009). Markov-switching DSGE and VAR models like Sims et al (2008) and Davig and Doh (2009), Farmer et al. (2009), Branchi (2012).  

#Capital flow
[International Capital Flows to emerging markets](http://www.sciencedirect.com/science/article/pii/S0261560615001941). Novel dataset to analyse gross and net capital flows. Advanced economy bond yields and commodity prices determine global capital flows. Financial openness and instututions important.  There are commmon volatilities in flows. [Here is a link](http://www.stevebronder.com/panic-vignette/) to the paper with the PANIC model. There is debate over whether global or domestic factors are the most important for capital flows. Calvo, Leiderman and Reinhart (1993), Reinhart and Reinhart (2009) look at global factors.  Contessi DePace and Francis (2009) find that international factors affect different types of capital flow in different ways. Domestic factor may also be important.  For example, human capital, financial openness and institutions. Rothenberg and Warnock (2011) argue that capital flow dynamics may come from inflows or outflows which are related to different factors. Findings: US long term interest rates are important for the bank flows; there is a role for commodity priecs and uncertainty in driving equity flows.  Financial openness and institutions are important for determining where these flows go.  


[Capital flows in emerging](http://www.citeulike.org/user/RobHayward/article/13841123)
How do capital flows change before and after the financial crisis? Do capital controls affect capital flows?  Dynamic panel model estimation. External factors are most important for emerging economies.  Short-term portfolio flow and long-term foreign direct investment affect emerging economy rates.  GFC caused accomodative policies that have created new challenges. Paper looks at the relationship between domestic factors and international factors affect the exchange rate.  For the latter, risk appetite, global liquidity, US monetary policy, commodity prices are used. This paper compliments the studie on the international aspect of US Fed quantitative easing and subsequent *tapering*. 

Capital flows are more important.  Short-term flows are prone to reversal (Ahmed and Zlate: 2014).  Unconventional policies encouraged the flow of capital from developed to emerging economies. 

The dynamic panel shows that market risk appetite, market liquidity and US monetary policy play a major role in driving exchange rate pressure. 

Exchange Market Pressure (EMP) is the term used here.  Limit literarture post crisis.  Ross and Spiegel (2009) and Frankel and Saravelos (2010) assess the degree to which leading indicators can provide information. 

Empirical evidence on the importance of capital flows:  Brooks et al (2001), Bakardzhiva at al. (2010) show that portfolio flows, borrowing and aid affect the real exchange rate. Combesa et al. (2012) assess real exchange rate for developed and emerging economies. 

Interest in external (push) and internal (pull) factors. Fred data on TED, VIX, bond yields, Fed funds rate and slope of the yield curve. Also use of Fernandez (2012) capital control data. 

EMP is measured as difference between the percentage change in the exchange rate and and foreign exchange reserves. Interest rate differential is added so that the total measure of pressure is 

$$emp_t = \frac{e_t - e_{t-1}}{e_{t-1}} - (i_t - i_t^*) - \frac{ir_t - ir_{t-1}}{ir+{t-1}}$$


[International liquidity and Exchange rate dynamics](http://www.citeulike.org/user/RobHayward/article/13828642). Exchange rates determined by capital flows. Supply and demand for capital and willingness of financial system to absorb imbalances determines exchange rates.  Risk-taking in currency markets is concentrated amongst a few niche financial institutions. These institutions range from proprietary desks of investment banks, hedge funds and active fund managers. Constrained by capital and balance sheet. Alterations in the financial balance sheets cause alterations in the pricing of currency risk. This introduces portfolio flows, financiers' balance sheets and risk into the determination of exchange rates. 

Stylised facts:  Failures of UIP and profitability of carry trade; large-scale gross capital flows; appreciation of exchange rates that face capital inflows; disconnect between exchange rates and macroeconomic fundamentals; vulnerability of external-debt currencies to financial shock; impact of large-scale intervention on exchange rates. UIP is violated because financiers' risk-bearing activity scope is limited and this requires them to demand a risk-premium. The carry-trade is profitable because, given an interest rate differential, financiers cannot take sufficient risk to exploit the profitability of the trade. Financial disruptions require an increased expected return via an immediate loss and an expectation of recovery ahead. Financiers act as shock absorbers by absorbing some of the imbalance caused by fundamentals but also cause shocks 

With goods prices sticky in domestic currency, a capital inflow that causes an appreciation of the exchange rate causes a fall in the demand for inflow-receiving country exports and a fall in output. The inflow of capital can therefore cause a reduction in output. 

This paper is related to 

* Early portfolio balance models: Kouri (1976), Diskill and McCafferty (1980).  Branson and Henderson (1985). There are a number of models that focus on UIP-based analysis or currency risk-premia in complete markets. 
* There are also exchange rate models in the face of frictions. 

Financiers intermediate the goods and bond demand of two representative countries. Capital flows from households move financiers up and down the demand curve.  Exchange rates are financially-determined. 

There is a construction that ensures that risk-taking is limited by the overall size of the positions and risk (as measured by the variance). This is build on the ideas used previously by Gertler and Kiyotaki (2010) and Maggiori (2014). Adrian and Shin (2013) provide foundations and empirical evidence for a VaR constraint that does similar work. This case is the *basic gamma model*.   The aggregate financial sector's optimal demand for dollar bonds vs yen bonds follows

$$Q_0 = \frac{1}{\Gamma} E \left [ e_0 - e_1\frac{R^*}{R} \right ]$$

where,$\Gamma = \gamma(var(e_1))^{\alpha}$. When $\Gamma = 0$, the financiers are willing to take any position and UIP holds; When $\Gamma \rightarrow \infty$ the financiers are unwilling to taken any positions. Between those two cases, there is some intermediation and UIP does not always hold. The deviations from UIP are related to financiers risk-taking. 

## Financial constraints
[Darrell Duffie](http://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.2010.01569.x/full) provides a model of securities prices adjustment to information that is based on slow-moving capital.  He cites the reaction of stocks to index exclusion, with price concession that has waned over time and the explanation that buyers initially requires a substantial price fall but as capital is employed to take advantage of this inefficiency, the price fall becomes more limited. Price impact is measured from the last execution price at $P_{t-1}$ to the lowest limit order buy that is hit by the market sell order. The price impact will increase with the size of the sell order. New orders will enter the market. Inference is drawn over whether the sale was motivated by private information or by liquidity motivation.  The first new limit order to buy will arrive opportunistically between last price executed and the valuation that is attached to the security. Gradually an assessment of the motivation of the seller and the value of the security emerge. Limit order prices and expected value will tend to converge and the price will tend to rise.  On average, the price is not expected to fully recover as some sell orders are based on new information. 

>If the balance-sheet capacity of dealers is depleted, their ability to intermediate markets is reduced.  They become less able or  predisposed to absorb supply and demand shocks, and to hold buffer inventories of assets.  When this happens, one expects the market value of risky assets to decline commensurately.  

The financial crisis provide an example of cases where the depletion of dealer capital was such that distortions in arbitrage-based pricing relationship appeared. For example, CDS and bond spreads. 

If investors are not really attentive to market prices at all times, the market is thinner in each moment and the price impact of traders will be larger. This would mean higher short-run volatility and negatively correlated asset returns. 

#Sudden Stops
[External Shocks and optimal monetary policy](http://www.bis.org/publ/work528.htm).  The GFC and feedback loops of capital outflow, currency depreciation and deteriorating balance sheets, rising credit spreads and reduced real activity for emerging economies. DSGE model with banking system open to domestic and overseas funding. The Ramsey-optimal policy rule suggests that there should be a response to leanding spreads over the cost of foreign debt, the exchange rate and US interest rates as well as local output and inflation. Reserve requirements can be as effective as policy response to interest rate spreads and the exchange rate. 

[Early warnings of banking crisis](http://www.sciencedirect.com/science/article/pii/S0261560615001928).  This is also in the citulike folder.  There is an exploration of fundamentals in the run up to banking crisis. An early warning system. Interaction of liqudity ratios and loss of demand deposits. Out-of-sample forecasts demonstrate strong predictive power. Table 1 has data from Laeven Valencia (2008), Valencia (2010) and Laeven Valendia (2012) on banking crises.  It is at the monthly level. The paper examines deviations in fundamentals from their norm in teh run up to these crises.  

There are four states of the economy: 
1. pre-crisis (12 months before); 
2. crisis (from crisis until read GDP and real credit growth are positive); 
3. post-crisis (the offset of the crisis and following 12 months); 
4. tranquile phase. Where there is no crisis in the preceeding or following 12 months. 

To deal with endogeneity, a binominal discrete dependent variable model is estimated. It identifies crisis and tanquile periods.

Need to look at Bussiere and Frantzsher (2006), Towards an early warning system of Financial Crises, Journal of International Money and Finance, 25 (6) 953-73. 

[Towards an early warning system of financial crisis](http://www.citeulike.org/user/RobHayward/article/13841902).  Paper developes an early warning system (EWS) based on a multinomial logit model. Binomial models are subject to *post-crisis bias*. This is the result of failing to distinguish between tranquile periods and the post-crisis period when variables are returning to fundamental levels after the shock. Correctly predicts crises in a majority of 1993-2001 period. 

IMF has helped to develop EMS for financial crisis. These have produced papers by Kaminsky et al. (1998) and Berg and Patillo (1999).  Also central banks: Kamin et al. (2001) and Kamin and Babson (1999) from Fed, Schnatz (1998 and 1999) Bundesbank.  Also private sector:  there is a list on page 954 including JP Morgan, Goldman Sachs, Deutsche Bank, Credit Suisse First Boston, Morgan Stanley. 

There are a number of different definitions of crisis: currency crisis, banking crisis, sovereign debt crisis, private debt crisis, equity crisis. Cuerrency crises are often related to other crises. Kaminsky and Reinhart (1999) identify a combination of currency and banking crisis as a natural combination. 

EMP variable is employed:

$$EMP_{i,t} = w_{REER} \left (\frac{REER_{i,t} - REER_{i, t-1}}{REER_{i, t-1}} \right ) + w_r (r_{i, t} - r_{i, t-1}) - w_{res} \left (\ \frac{res_{i, t} - r_{i, t-1}}{r_{i, t-1}} \right ) $$

It is a weighted average of the change in the real, effective exchange rate, the change in the interest rate and the change in reserves. The importance of EMP is that it captures successful and unsuccessful speculative attacks. A currency crisis is defined as those times when The EMP is two standard deviations above its average value. 

$$  CC_{i, t} = 
    \begin{cases}
    1 \text{ if } EMP_{i, t} > \bar{EMP_i} + 2SD(EMP_i)\\
    0 \text{ if otherwise}
    \end{cases}
   $$
This is a definition of currency crisis that is very commonly used in the literature. See for example, Schnatz (1998) for a through discussion. 

There are two aspects to finding EWS:

* Determining whether a crisis will occure
* Determining when the crisis will occure

The second is much harder. Therefore, it is usual to determine whether a crisis happens in a specific time frame.  In this paper, there is an attempt to cetermine if a crisis will happen in the next 6 months. Therefore, the $C_{i, t}$ variable is transformed into a forward looking variable $Y_{i, t}

$$ Y_{i, t} = 
    \begin{cases}
    1 \text{ if } \exists k = 1, \dots, 12 s.t. CC_{i, t} = 1\\
    0 \text{ otherwise}
    \end{cases}
$$

There are two other broad categories of EWS for currency rates.  

* Extract signals from a range of indicators: Kaminsky and Reinhart (1999), Kaminsky et al. (1998), Goldstein et al. (2000).  The indicators provide a signal when a threashold is breached. The threshold is then adjusted to loewr the noise to signal ratio. 
* Use of logit or probit models: Frankel and Rose (1996), Eichengreen et al. (1995) and Berg and Patillo (1996). Does not throw away information by turing discreate or continuous variables into binary variables. 

Good overview of logistic model (page 956-7). 

Threshold is based on the trade off between the damage caused by Type I and Type II erros. 

The variables included in the model include degree of overvaluation of the exchange rate (based on change over the last two years, current account, short-term debt to reserves ratio, domestic credit growth, real GDP growth and financial  contaigion. 

The conditional probability of a crisis given a signal is 35%.  This compares to 15.8\% for the unconditional probability. 

[Can intervention stem exchange rate pressure](http://www.imf.org/external/pubs/cat/longres.aspx?sk=43090.0)
FX intervention for emerging economies as a response to gross capital inflow. Has this been an effective tool? FX leads to less exchange rate appreciation. FX intervention can affect the exchange rate through a signalling channel and a portfolio balance channel. Portfolio balance channel Henderson Rogoff (1982), Kouri (1983) and Branson and Henderson (1985).  See Kumhof (2010) and Gabaix Maggiori (2014) for recent advances. 

Rey (2013) and de Carvalho (2014) find the VIX to be a good proxy for global financial flows. 


[Capital flow Bonanzas (Reinhart)](http://econpapers.repec.org/paper/nbrnberwo/14321.htm)
This paper catalogues capital inflow bonanzas for the period 1960 to 2007 for 181 countries. Finding that global factors such as commodity prices, international interest rates and growth in the world's largest economies have a systematic effect on the capital flow cycle. Capital inflow bonanzas are associated with higher likelihood of economic crisis (debt defaults, banking, inflation and currency crashes). 
[Blanchard](http://www.citeulike.org/pdf//user/RobHayward/article/13818723}{CitULike)

Are capital flows expansionary - Blanchard, Ostry, Ghost and Chamon. 

The traditional open-economy model suggests that capital in-flows are contraction (as the appreciation of the exchange rate reduces net exports).  However, policy-makers believe that they are expansionary as they increase credit and raise asset prices.  An augmented Mundell-Flemming model, including bonds and non-bonds, allows an inflow to reduce the rate on bonds and an expansionary reduction in the cost of financial intermediation.  This can offset contractionary effects.  There are of course (according to me) some sectoral distributive effects. 

This is based on models of Mundell (1963), Flemming (1962) and Dornbusch (1976). 

Ostry (2012) looks at effect of capital controls during the financial crisis. Reinhard and Rogoff (2009) show that capital flows played a major role in driving boom-bust cycles. 

Bonds and non-bonds.  Here non-bonds are stocks and bank deposits (imperfect substitutes).  The policy rate (bonds) may be given but capital inflows can reduce the rate on non-bonds (driving up equity prices and flooding the banking system with cash).   

Implications:  effect of capital flows depends on the nature of the flow.  For a given policy rate, bond inflows lead only to an exchange rate appreciation and are therefore contractionary.  However, non-bond flows lead to an appreciation and a fall in the rate of return. 

Sterilized intervention through bonds can fully offset the effect of capital inflow to the bond market. The central bank offsets the foreign influence. When the central bank faces a inflow to non-bonds, the intervention can prevent appreciation but reduces the rate of return on non-bonds. 

What are the extensions:  lower returns on non-bonds can mean an increase in credit growth (also equity and real estate bubbles).  Distortions include real (Dutch disease) and financial (bubbles). Policy tools that target the type of flow (such as intervention and capital controls) are more effective than tools that do not (interest rate). 

Three major types of non-bonds:  FDI, domestic equities and domestic bank liabilities. There must be imperfect substituatility between domestic bonds, domestic non-bonds and foreign bonds so that different rates do not lead to infinite capital flows. 
IMF, Hyun Song Shin, 
     [IMF](https://www.imf.org/external/pubs/ft/wp/2013/wp13258.pdf)

Search for early warning indicators.  . Three early warnings:  financial market prices (CDS spreads, implied volatility and other prices), level of credit (relative to GDP) and liabilities of financial intermediaries (money growth).  Credit and provide some warning while asset prices are more concurrent.

Literature is either eclectic or pragmatic says Shin. Kaminsky, Lizondo and Reinhart 1998) identify 105 variables that have been used. 

Emerging economies are more associated with sudden stops. 

There is an overview from Chamon and Crowe (2012).  

Emerging market crisis of 1990 provided impetus to the work. GFC as well. 

 IMF has a Vulnerability Exercise for Emerging Economies (VEE). 

BIS: Evaluating the early warning indicators of banking crisis: satisfying policy requirements,. . Assessment of early warning indicators (EWI).  Value of credit-to-GDP gap and debt-service ratio outperform other measures. 

[BIS](http://www.bis.org/publ/work421.pdf)
Mathias Drehmann and Mikael Juselius

The indicators must come early enough to be useful.

Kaminsky and Reinhart (2000). Signal extraction based on methodology developed from Diebold and Rudebusch (1989) and Stock and Watson (1989). 

##Case study Hungary
[Ecofin Research](http://ec.europa.eu/economy_finance/publications/publication1409_en.pdf).  Comprehensive reform began in 1995.  This included reductions in government spending and a pre-announced crawling peg with fluctuation bands of 2.25\% of the forint against a basket. However, by 2001 policy orientation began to reverse with larger budget deficits.  There were large imbalances by 2003. The central bank had to increase interest rates by 600bp in 2003, taking the policy rate to 12.5\%.   The policy mix turned from tight-fiscal and loose-money to loose-fiscal and tight-money. The 2001 to 2002 period, described by this paper as the "root of the problem" (p3).  Minimum wages were doubled. Currency appreciated to reach the upper end of the fluctuation band. The current account deficit reached 5.5\% of GDP In 2003. 

By the end of 2002, there was a speculative attack against the strong side of the band, buoyed by high interest rates, sting economic growth and forthcoming EU accession. Speculative attack addressed by 200bp rate cut and some other measures (what are these?).  In June 2003, the government devalued the central parity against the euro by 2.26% and increased the fluctuation bands to 15\%.  A speculative attack on the currency was met by a 300bp increase in interest rates (June 2003). In November 2003, poor economic news (fiscal) cause another outflow, a 4-month low and a 300bp increase in interest rates (12.5\%)

Others:  Poland suffered significant depreciation during 2008Q4 to 2009Q1. 
This time it is different:  2008 currency crisis defined as Latvia, Ukraine, Hungary, Russia. Capital flows and currency crisis table. 

17.1 early warning of currency crisis. What are the alternative.s 
